// <auto-generated />
using System;
using Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CuidaPetWeb.Migrations
{
    [DbContext(typeof(CuidaPetContext))]
    partial class CuidaPetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Agendamento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("date")
                        .HasColumnName("dataConfirmacao");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("date")
                        .HasColumnName("dataSolicitacao");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time")
                        .HasColumnName("horario");

                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.Property<uint>("IdPet")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPet");

                    b.Property<uint>("IdTutor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idTutor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('S','A','C','R')")
                        .HasColumnName("status")
                        .HasComment("S (Solicitado), A (Aprovado), C (Cancelado), R (Realizado)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdTutor" }, "fk_Agendamento_Pessoa1_idx");

                    b.HasIndex(new[] { "IdPet" }, "idPet");

                    b.HasIndex(new[] { "IdFuncionario" }, "idVeterinario");

                    b.ToTable("agendamento", (string)null);
                });

            modelBuilder.Entity("Core.Categoria", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("Core.Consulta", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Anotacoes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("anotacoes");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime")
                        .HasColumnName("dataConsulta");

                    b.Property<uint>("IdAgendamento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idAgendamento");

                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.Property<uint>("IdPet")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPet");

                    b.Property<uint>("IdTutor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idTutor");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAgendamento" }, "fk_Consulta_Agendamento1_idx");

                    b.HasIndex(new[] { "IdFuncionario" }, "fk_Consulta_Funcionario2_idx");

                    b.HasIndex(new[] { "IdTutor" }, "fk_Consulta_Pessoa1_idx");

                    b.HasIndex(new[] { "IdPet" }, "fk_Consulta_Pet1_idx");

                    b.ToTable("consulta", (string)null);
                });

            modelBuilder.Entity("Core.Doenca", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("IdEspecie")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEspecie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEspecie" }, "idEspecie");

                    b.ToTable("doenca", (string)null);
                });

            modelBuilder.Entity("Core.Especialidade", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("especialidade", (string)null);
                });

            modelBuilder.Entity("Core.Especie", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("especie", (string)null);
                });

            modelBuilder.Entity("Core.Estabelecimento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("char(14)")
                        .HasColumnName("CNPJ")
                        .IsFixedLength();

                    b.Property<string>("Complemento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("complemento");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("estado")
                        .IsFixedLength();

                    b.Property<uint>("IdGerente")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idGerente");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .HasColumnType("enum('C','P','A')")
                        .HasColumnName("tipo")
                        .HasComment("C(Clínica), P(Petshop), A(Ambos)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cnpj" }, "CNPJ")
                        .IsUnique();

                    b.HasIndex(new[] { "IdGerente" }, "fk_Estabelecimento_Pessoa1_idx");

                    b.ToTable("estabelecimento", (string)null);
                });

            modelBuilder.Entity("Core.Funcionario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Crmv")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("crmv");

                    b.Property<uint>("IdEstabelecimento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEstabelecimento");

                    b.Property<uint>("IdPessoa")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPessoa");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Crmv" }, "crmv")
                        .IsUnique();

                    b.HasIndex(new[] { "IdEstabelecimento" }, "fk_Funcionario_Estabelecimento1_idx");

                    b.HasIndex(new[] { "IdPessoa" }, "idUsuario")
                        .IsUnique();

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("Core.Horariosatendimento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("enum('DOM','SEG','TER','QUA','QUI','SEX','SAB')")
                        .HasColumnName("diaSemana")
                        .HasComment("\n");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time")
                        .HasColumnName("horario");

                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFuncionario" }, "idVeterinario")
                        .HasDatabaseName("idVeterinario1");

                    b.ToTable("horariosatendimento", (string)null);
                });

            modelBuilder.Entity("Core.Notificacao", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime")
                        .HasColumnName("dataEnvio");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("notificacao", (string)null);
                });

            modelBuilder.Entity("Core.Pedido", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("IdAgendamento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idAgendamento");

                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.Property<uint>("IdTutor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idTutor");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("realizadoEm");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('A','F','C')")
                        .HasColumnName("status")
                        .HasComment("A = Andamento, F = Finalizado, C = Cancelado");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdAgendamento" }, "fk_Pedido_Agendamento1_idx");

                    b.HasIndex(new[] { "IdFuncionario" }, "fk_Pedido_Funcionario1_idx");

                    b.HasIndex(new[] { "IdTutor" }, "idUsuario")
                        .HasDatabaseName("idUsuario1");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("Core.Pedidoproduto", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("IdPedido")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPedido");

                    b.Property<uint>("IdProduto")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idProduto");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPedido" }, "idPedido");

                    b.HasIndex(new[] { "IdProduto" }, "idProduto");

                    b.ToTable("pedidoproduto", (string)null);
                });

            modelBuilder.Entity("Core.Pessoa", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("estado")
                        .IsFixedLength();

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("senha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('A','I')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'A'")
                        .HasComment("A (Ativo), I (Inativo)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("telefone")
                        .IsFixedLength();

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("enum('T','G','A','V','Ad')")
                        .HasColumnName("tipo")
                        .HasComment("T (Tutor), G (Gerente), A (Atendente), V (Veterinário), Ad (Administrador)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Cpf" }, "cpf_UNIQUE")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Telefone" }, "telefone_UNIQUE")
                        .IsUnique();

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("Core.Pessoanotificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<uint>("IdNotificacao")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idNotificacao");

                    b.Property<uint>("IdPessoa")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPessoa");

                    b.Property<sbyte>("StatusLida")
                        .HasColumnType("tinyint")
                        .HasColumnName("statusLida")
                        .HasComment("0 - Não lida, 1 - Lida");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdNotificacao" }, "fk_Pessoa_has_Notificacao_Notificacao1_idx");

                    b.HasIndex(new[] { "IdPessoa" }, "fk_Pessoa_has_Notificacao_Pessoa1_idx");

                    b.ToTable("pessoanotificacao", (string)null);
                });

            modelBuilder.Entity("Core.Pessoapet", b =>
                {
                    b.Property<uint>("IdPessoa")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPessoa");

                    b.Property<uint>("IdPet")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPet");

                    b.HasIndex(new[] { "IdPessoa" }, "fk_Pet_has_Pessoa_Pessoa1_idx");

                    b.HasIndex(new[] { "IdPet" }, "fk_Pet_has_Pessoa_Pet1_idx");

                    b.ToTable("pessoapet", (string)null);
                });

            modelBuilder.Entity("Core.Pet", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("dataNascimento");

                    b.Property<uint>("IdRaca")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idRaca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("enum('M','F')")
                        .HasColumnName("sexo")
                        .HasComment("M (Macho), F (Fêmea)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRaca" }, "fk_Pet_Raca1_idx");

                    b.ToTable("pet", (string)null);
                });

            modelBuilder.Entity("Core.Petdoenca", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataDiagnostico")
                        .HasColumnType("date")
                        .HasColumnName("dataDiagnostico");

                    b.Property<uint>("IdDoenca")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idDoenca");

                    b.Property<uint>("IdPet")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPet");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDoenca" }, "idDoenca");

                    b.HasIndex(new[] { "IdPet" }, "idPet")
                        .HasDatabaseName("idPet1");

                    b.ToTable("petdoenca", (string)null);
                });

            modelBuilder.Entity("Core.Produto", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descricao");

                    b.Property<uint>("IdCategoria")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idCategoria");

                    b.Property<uint>("IdEstabelecimento")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEstabelecimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.Property<decimal?>("PrecoPromocao")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precoPromocao");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('I','D','P')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'D'")
                        .HasComment("I (Indisponível), D (Disponível), P (Promoção)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEstabelecimento" }, "fk_produto_estabelecimento1_idx");

                    b.HasIndex(new[] { "IdCategoria" }, "idCategoria");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("Core.Raca", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("IdEspecie")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEspecie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEspecie" }, "idEspecie")
                        .HasDatabaseName("idEspecie1");

                    b.ToTable("raca", (string)null);
                });

            modelBuilder.Entity("Core.UsuarioIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Core.Vacina", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<uint>("IdDoenca")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idDoenca");

                    b.Property<uint>("IdEspecie")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEspecie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<ushort?>("PeriodoEmDias")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("periodoEmDias");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEspecie" }, "fk_Vacina_Especie1_idx");

                    b.HasIndex(new[] { "IdDoenca" }, "idDoenca")
                        .HasDatabaseName("idDoenca1");

                    b.ToTable("vacina", (string)null);
                });

            modelBuilder.Entity("Core.Vacinacao", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataVacina")
                        .HasColumnType("date")
                        .HasColumnName("dataVacina");

                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.Property<uint>("IdPet")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idPet");

                    b.Property<uint>("IdTutor")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idTutor");

                    b.Property<uint>("IdVacina")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idVacina");

                    b.Property<string>("Lote")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lote");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFuncionario" }, "fk_VacinaPet_Funcionario1_idx");

                    b.HasIndex(new[] { "IdTutor" }, "fk_Vacinacao_Pessoa1_idx");

                    b.HasIndex(new[] { "IdPet" }, "idPet")
                        .HasDatabaseName("idPet2");

                    b.HasIndex(new[] { "IdVacina" }, "idVacina");

                    b.ToTable("vacinacao", (string)null);
                });

            modelBuilder.Entity("Funcionarioespecialidade", b =>
                {
                    b.Property<uint>("IdFuncionario")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idFuncionario");

                    b.Property<uint>("IdEspecialidade")
                        .HasColumnType("int unsigned")
                        .HasColumnName("idEspecialidade");

                    b.HasKey("IdFuncionario", "IdEspecialidade")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEspecialidade" }, "fk_Funcionario_has_Especialidade_Especialidade1_idx");

                    b.HasIndex(new[] { "IdFuncionario" }, "fk_Funcionario_has_Especialidade_Funcionario1_idx");

                    b.ToTable("funcionarioespecialidade", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Agendamento", b =>
                {
                    b.HasOne("Core.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("agendamento_ibfk_2");

                    b.HasOne("Core.Pet", "IdPetNavigation")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdPet")
                        .IsRequired()
                        .HasConstraintName("agendamento_ibfk_1");

                    b.HasOne("Core.Pessoa", "IdTutorNavigation")
                        .WithMany("Agendamentos")
                        .HasForeignKey("IdTutor")
                        .IsRequired()
                        .HasConstraintName("fk_Agendamento_Pessoa1");

                    b.Navigation("IdFuncionarioNavigation");

                    b.Navigation("IdPetNavigation");

                    b.Navigation("IdTutorNavigation");
                });

            modelBuilder.Entity("Core.Consulta", b =>
                {
                    b.HasOne("Core.Agendamento", "IdAgendamentoNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdAgendamento")
                        .IsRequired()
                        .HasConstraintName("fk_Consulta_Agendamento1");

                    b.HasOne("Core.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("fk_Consulta_Funcionario2");

                    b.HasOne("Core.Pet", "IdPetNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdPet")
                        .IsRequired()
                        .HasConstraintName("fk_Consulta_Pet1");

                    b.HasOne("Core.Pessoa", "IdTutorNavigation")
                        .WithMany("Consulta")
                        .HasForeignKey("IdTutor")
                        .IsRequired()
                        .HasConstraintName("fk_Consulta_Pessoa1");

                    b.Navigation("IdAgendamentoNavigation");

                    b.Navigation("IdFuncionarioNavigation");

                    b.Navigation("IdPetNavigation");

                    b.Navigation("IdTutorNavigation");
                });

            modelBuilder.Entity("Core.Doenca", b =>
                {
                    b.HasOne("Core.Especie", "IdEspecieNavigation")
                        .WithMany("Doencas")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("doenca_ibfk_1");

                    b.Navigation("IdEspecieNavigation");
                });

            modelBuilder.Entity("Core.Estabelecimento", b =>
                {
                    b.HasOne("Core.Pessoa", "IdGerenteNavigation")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("IdGerente")
                        .IsRequired()
                        .HasConstraintName("fk_Estabelecimento_Pessoa1");

                    b.Navigation("IdGerenteNavigation");
                });

            modelBuilder.Entity("Core.Funcionario", b =>
                {
                    b.HasOne("Core.Estabelecimento", "IdEstabelecimentoNavigation")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdEstabelecimento")
                        .IsRequired()
                        .HasConstraintName("fk_Funcionario_Estabelecimento1");

                    b.HasOne("Core.Pessoa", "IdPessoaNavigation")
                        .WithOne("Funcionario")
                        .HasForeignKey("Core.Funcionario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("veterinario_ibfk_2");

                    b.Navigation("IdEstabelecimentoNavigation");

                    b.Navigation("IdPessoaNavigation");
                });

            modelBuilder.Entity("Core.Horariosatendimento", b =>
                {
                    b.HasOne("Core.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Horariosatendimentos")
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("horariosatendimento_ibfk_1");

                    b.Navigation("IdFuncionarioNavigation");
                });

            modelBuilder.Entity("Core.Pedido", b =>
                {
                    b.HasOne("Core.Agendamento", "IdAgendamentoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdAgendamento")
                        .IsRequired()
                        .HasConstraintName("fk_Pedido_Agendamento1");

                    b.HasOne("Core.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("fk_Pedido_Funcionario1");

                    b.HasOne("Core.Pessoa", "IdTutorNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdTutor")
                        .IsRequired()
                        .HasConstraintName("pedido_ibfk_1");

                    b.Navigation("IdAgendamentoNavigation");

                    b.Navigation("IdFuncionarioNavigation");

                    b.Navigation("IdTutorNavigation");
                });

            modelBuilder.Entity("Core.Pedidoproduto", b =>
                {
                    b.HasOne("Core.Pedido", "IdPedidoNavigation")
                        .WithMany("Pedidoprodutos")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("produtopedido_ibfk_2");

                    b.HasOne("Core.Produto", "IdProdutoNavigation")
                        .WithMany("Pedidoprodutos")
                        .HasForeignKey("IdProduto")
                        .IsRequired()
                        .HasConstraintName("produtopedido_ibfk_1");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProdutoNavigation");
                });

            modelBuilder.Entity("Core.Pessoanotificacao", b =>
                {
                    b.HasOne("Core.Notificacao", "IdNotificacaoNavigation")
                        .WithMany("Pessoanotificacaos")
                        .HasForeignKey("IdNotificacao")
                        .IsRequired()
                        .HasConstraintName("fk_Pessoa_has_Notificacao_Notificacao1");

                    b.HasOne("Core.Pessoa", "IdPessoaNavigation")
                        .WithMany("Pessoanotificacaos")
                        .HasForeignKey("IdPessoa")
                        .IsRequired()
                        .HasConstraintName("fk_Pessoa_has_Notificacao_Pessoa1");

                    b.Navigation("IdNotificacaoNavigation");

                    b.Navigation("IdPessoaNavigation");
                });

            modelBuilder.Entity("Core.Pessoapet", b =>
                {
                    b.HasOne("Core.Pessoa", "IdPessoaNavigation")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .IsRequired()
                        .HasConstraintName("fk_Pet_has_Pessoa_Pessoa1");

                    b.HasOne("Core.Pet", "IdPetNavigation")
                        .WithMany()
                        .HasForeignKey("IdPet")
                        .IsRequired()
                        .HasConstraintName("fk_Pet_has_Pessoa_Pet1");

                    b.Navigation("IdPessoaNavigation");

                    b.Navigation("IdPetNavigation");
                });

            modelBuilder.Entity("Core.Pet", b =>
                {
                    b.HasOne("Core.Raca", "IdRacaNavigation")
                        .WithMany("Pets")
                        .HasForeignKey("IdRaca")
                        .IsRequired()
                        .HasConstraintName("fk_Pet_Raca1");

                    b.Navigation("IdRacaNavigation");
                });

            modelBuilder.Entity("Core.Petdoenca", b =>
                {
                    b.HasOne("Core.Doenca", "IdDoencaNavigation")
                        .WithMany("Petdoencas")
                        .HasForeignKey("IdDoenca")
                        .IsRequired()
                        .HasConstraintName("petdoenca_ibfk_2");

                    b.HasOne("Core.Pet", "IdPetNavigation")
                        .WithMany("Petdoencas")
                        .HasForeignKey("IdPet")
                        .IsRequired()
                        .HasConstraintName("petdoenca_ibfk_1");

                    b.Navigation("IdDoencaNavigation");

                    b.Navigation("IdPetNavigation");
                });

            modelBuilder.Entity("Core.Produto", b =>
                {
                    b.HasOne("Core.Categoria", "IdCategoriaNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("produto_ibfk_1");

                    b.HasOne("Core.Estabelecimento", "IdEstabelecimentoNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdEstabelecimento")
                        .IsRequired()
                        .HasConstraintName("fk_produto_estabelecimento1");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdEstabelecimentoNavigation");
                });

            modelBuilder.Entity("Core.Raca", b =>
                {
                    b.HasOne("Core.Especie", "IdEspecieNavigation")
                        .WithMany("Racas")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("raca_ibfk_1");

                    b.Navigation("IdEspecieNavigation");
                });

            modelBuilder.Entity("Core.Vacina", b =>
                {
                    b.HasOne("Core.Doenca", "IdDoencaNavigation")
                        .WithMany("Vacinas")
                        .HasForeignKey("IdDoenca")
                        .IsRequired()
                        .HasConstraintName("vacina_ibfk_1");

                    b.HasOne("Core.Especie", "IdEspecieNavigation")
                        .WithMany("Vacinas")
                        .HasForeignKey("IdEspecie")
                        .IsRequired()
                        .HasConstraintName("fk_Vacina_Especie1");

                    b.Navigation("IdDoencaNavigation");

                    b.Navigation("IdEspecieNavigation");
                });

            modelBuilder.Entity("Core.Vacinacao", b =>
                {
                    b.HasOne("Core.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Vacinacaos")
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("fk_VacinaPet_Funcionario1");

                    b.HasOne("Core.Pet", "IdPetNavigation")
                        .WithMany("Vacinacaos")
                        .HasForeignKey("IdPet")
                        .IsRequired()
                        .HasConstraintName("vacinapet_ibfk_2");

                    b.HasOne("Core.Pessoa", "IdTutorNavigation")
                        .WithMany("Vacinacaos")
                        .HasForeignKey("IdTutor")
                        .IsRequired()
                        .HasConstraintName("fk_Vacinacao_Pessoa1");

                    b.HasOne("Core.Vacina", "IdVacinaNavigation")
                        .WithMany("Vacinacaos")
                        .HasForeignKey("IdVacina")
                        .IsRequired()
                        .HasConstraintName("vacinapet_ibfk_1");

                    b.Navigation("IdFuncionarioNavigation");

                    b.Navigation("IdPetNavigation");

                    b.Navigation("IdTutorNavigation");

                    b.Navigation("IdVacinaNavigation");
                });

            modelBuilder.Entity("Funcionarioespecialidade", b =>
                {
                    b.HasOne("Core.Especialidade", null)
                        .WithMany()
                        .HasForeignKey("IdEspecialidade")
                        .IsRequired()
                        .HasConstraintName("fk_Funcionario_has_Especialidade_Especialidade1");

                    b.HasOne("Core.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .IsRequired()
                        .HasConstraintName("fk_Funcionario_has_Especialidade_Funcionario1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Core.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Core.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Core.UsuarioIdentity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Agendamento", b =>
                {
                    b.Navigation("Consulta");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Core.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Core.Doenca", b =>
                {
                    b.Navigation("Petdoencas");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("Core.Especie", b =>
                {
                    b.Navigation("Doencas");

                    b.Navigation("Racas");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("Core.Estabelecimento", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Core.Funcionario", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Consulta");

                    b.Navigation("Horariosatendimentos");

                    b.Navigation("Pedidos");

                    b.Navigation("Vacinacaos");
                });

            modelBuilder.Entity("Core.Notificacao", b =>
                {
                    b.Navigation("Pessoanotificacaos");
                });

            modelBuilder.Entity("Core.Pedido", b =>
                {
                    b.Navigation("Pedidoprodutos");
                });

            modelBuilder.Entity("Core.Pessoa", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Consulta");

                    b.Navigation("Estabelecimentos");

                    b.Navigation("Funcionario");

                    b.Navigation("Pedidos");

                    b.Navigation("Pessoanotificacaos");

                    b.Navigation("Vacinacaos");
                });

            modelBuilder.Entity("Core.Pet", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Consulta");

                    b.Navigation("Petdoencas");

                    b.Navigation("Vacinacaos");
                });

            modelBuilder.Entity("Core.Produto", b =>
                {
                    b.Navigation("Pedidoprodutos");
                });

            modelBuilder.Entity("Core.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Core.Vacina", b =>
                {
                    b.Navigation("Vacinacaos");
                });
#pragma warning restore 612, 618
        }
    }
}
